name: conda environment for ASH
#Only conda-forge allowed for now
channels:
  - conda-forge
#Some basic easy-to-install packages for ASH
dependencies:
  - python=3.11
  - pip
  - openmm
  - pdbfixer
  - mdtraj
  - numpy
  - xtb
  - xtb-python
  - typing_extensions
  - rdkit
  - pip:
    - geometric
    - pyscf
