#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#Note: python-jl fix so that PyJulia works without problems
#Note: This file needs to be made executable: chmod +x python3_ash
import sys
import re

from julia.python_jl import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())