coverage:
  ignore:
    - geometric/tests/.*
    - geometric/PDB.py
    - geometric/_version.py
    - docs/*
    - setup.py
  status:
    patch: false
  range: 60..90
  round: nearest
  precision: 1
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null
