name: Python Package using Conda

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "NEW"
      - "master"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
          conda --version
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
          conda env update --file environment.yml --name base
          conda list
      - name: check stuff
        run: |
           which python
           which conda
           which mamba
           which pip
           echo $PATH
           which xtb
      - name: Lint with flake8
        run: |
          conda install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          conda install pytest
          which python
          pwd
          ls
          pytest -v 
